export const CREATE_POST_REQUEST="CREATE_USER_REQUEST";
export const CREATE_POST_SUCCESS="CREATE_POST_SUCCESS";
export const CREATE_POST_FAIL="CREATE_POST_FAIL";

export const GET_POST_REQUEST="GET_USER_REQUEST";
export const GET_POST_SUCCESS="GET_POST_SUCCESS";
export const GET_POST_FAIL="GET_POST_FAIL";

export const GET_POSTS_REQUEST="GET_POSTS_REQUEST";
export const GET_POSTS_SUCCESS="GET_POSTS_SUCCESS";
export const GET_POSTS_FAIL="GET_POSTS_FAIL";

export const GET_TIME_LINE_POSTS_REQUEST="GET_TIME_LINE_POSTS_REQUEST";
export const GET_TIME_LINE_POSTS_SUCCESS="GET_TIME_LINE_POSTS_SUCCESS";
export const GET_TIME_LINE_POSTS_FAIL="GET_TIME_LINE_POSTS_FAIL";

export const DELETE_POST_REQUEST="DELETE_POST_REQUEST";
export const DELETE_POST_SUCCESS="DELETE_POST_SUCCESS";
export const DELETE_POST_FAIL="DELETE_POST_FAIL";

export const UPDATE_POST_REQUEST="UPDATE_POST_REQUEST";
export const UPDATE_POST_SUCCESS="UPDATE_POST_SUCCESS";
export const UPDATE_POST_FAIL="UPDATE_POST_FAIL";

export const LIKE_POST_REQUEST="LIKE_POST_REQUEST";
export const LIKE_POST_SUCCESS="LIKE_POST_SUCCESS";
export const LIKE_POST_FAIL="LIKE_POST_FAIL";