export const USER_LOGIN_REQUEST="USER_LOGIN_REQUEST";
export const USER_LOGIN_SUCCESS="USER_LOGIN_SUCCESS";
export const USER_LOGIN_FAIL="USER_LOGIN_FAIL";
export const USER_LOGOUT="USER_LOGOUT";

export const USER_REGISTER_REQUEST="USER_REGISTER_REQUEST";
export const USER_REGISTER_SUCCESS="USER_REGISTER_SUCCESS";
export const USER_REGISTER_FAIL="USER_REGISTER_FAIL";

export const GET_USER_REQUEST="GET_USER_REQUEST";
export const GET_USER_SUCCESS="GET_USER_SUCCESS";
export const GET_USER_FAIL="GET_USER_FAIL";

export const GET_USERS_REQUEST="GET_USERS_REQUEST";
export const GET_USERS_SUCCESS="GET_USERS_SUCCESS";
export const GET_USERS_FAIL="GET_USERS_FAIL";

export const DELETE_USER_REQUEST="DELETE_USER_REQUEST";
export const DELETE_USER_SUCCESS="DELETE_USER_SUCCESS";
export const DELETE_USER_FAIL="DELETE_USER_FAIL";

export const UPDATE_USER_REQUEST="UPDATE_USER_REQUEST";
export const UPDATE_USER_SUCCESS="UPDATE_USER_SUCCESS";
export const UPDATE_USER_FAIL="UPDATE_USER_FAIL";

export const FOLLOW_USER_REQUEST="FOLLOW_USER_REQUEST";
export const FOLLOW_USER_SUCCESS="FOLLOW_USER_SUCCESS";
export const FOLLOW_USER_FAIL="FOLLOW_USER_FAIL";

export const UNFOLLOW_USER_REQUEST="UNFOLLOW_USER_REQUEST";
export const UNFOLLOW_USER_SUCCESS="UNFOLLOW_USER_SUCCESS";
export const UNFOLLOW_USER_FAIL="UNFOLLOW_USER_FAIL";